spring:
 application: 
  name: ForumHub
  
 datasource:
  url: jdbc:mysql://192.168.1.1/forumhub_api
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: username
  password: 123123
  
 jpa:
  show-sql: true
  properties:
   hibernate:
    format_sql: true

 data:
  web:
   pageable: 
    page-parameter: page
    size-parameter: size

  sort:
   sort-parameter: sort
   
server:
 error:
  include-stacktrace: never
  
api:
 security:
  token:
   secret: ${JWT_SECRET:123123}